function request = otfs_tr_load_software_config(filePath, cfg)
%otfs_tr_load_software_config Read the software's key=value TXT request.
% The supplied sample is GBK encoded; UTF-8 files are also accepted.
% testPayload names a local MAT test-case file, not transmitted text.

if nargin < 2
    cfg = otfs_tr_config();
end
filePath = string(filePath);
allowedKeys = ["testPayload", "scenario", "freq_offset_hz", ...
    "targetBer", "targetSpectralEfficiency", ...
    "duration_seconds"];
values = otfs_tr_read_key_value_file(filePath, allowedKeys);
if ~isfield(values, "freq_offset_hz")
    error("otfs_tr:MissingSoftwareConfigKey", ...
        "Software configuration requires freq_offset_hz.");
end
if ~isfield(values, "testPayload") || ...
        strlength(values.testPayload) == 0
    error("otfs_tr:MissingTestCasePath", ...
        "Software configuration requires testPayload=<MAT file path>.");
end
testCasePath = values.testPayload;
isAbsolutePath = ~isempty(regexp(char(testCasePath), ...
    '^[A-Za-z]:[\\/]|^\\\\|^/', 'once'));
if ~isAbsolutePath
    testCasePath = fullfile(fileparts(filePath), testCasePath);
end
if ~isfile(testCasePath)
    error("otfs_tr:MissingTestCaseFile", ...
        "testPayload must identify an existing MAT file: %s", ...
        testCasePath);
end

request = struct("protocol_version", cfg.controlProtocolVersion, ...
    "command", "start_test", ...
    "test_case_file", string(testCasePath), ...
    "equivalent_cfo_hz", localNumber(values.freq_offset_hz, ...
        "freq_offset_hz"), ...
    "scenario_name", localValue(values, "scenario", cfg.scenarioName), ...
    "target_ber", localNumber(localValue(values, "targetBer", ...
        string(cfg.maximumBer)), "targetBer"), ...
    "target_spectral_efficiency", localNumber(localValue(values, ...
        "targetSpectralEfficiency", ...
        string(cfg.minimumSpectralEfficiency)), ...
        "targetSpectralEfficiency"), ...
    "options", struct("duration_seconds", localNumber( ...
        localValue(values, "duration_seconds", ...
        string(cfg.defaultTransmitDurationSeconds)), ...
        "duration_seconds")));
request = otfs_tr_validate_request(request, cfg);
end

function value = localValue(values, key, defaultValue)
if isfield(values, key)
    value = values.(key);
else
    value = defaultValue;
end
end

function value = localNumber(textValue, key)
value = str2double(textValue);
if ~isscalar(value) || ~isfinite(value)
    error("otfs_tr:InvalidSoftwareConfigNumber", ...
        "%s must contain one finite numeric value.", key);
end
end
