function otfs_tr_validate_config(cfg)
%otfs_tr_validate_config Reject unsupported or unsafe OTFS-TR settings.

requiredFields = [
    "txAddress", "rxAddress", "txRadioConfiguration", ...
    "rxRadioConfiguration", "txAntenna", "rxAntenna", ...
    "masterClockRate", "fsTx", "fsRx", ...
    "signalBandwidthHz", "N", "M", "MMod", "MBits", "cpLen", ...
    "preambleLen", "preambleRoot", "txBufferFrameCount", ...
    "rxSamplesPerFrame", "maxDecodedFrames", "minimumValidFrames", ...
    "availableCaptureFrames", "decodeFrameMarginRatio", ...
    "cfoSearchHz", "cfoFineSearchStepHz", "equivalentDopplerHz", ...
    "txTransportDataType", "rxTransportDataType"
    ];
for fieldIndex = 1:numel(requiredFields)
    fieldName = requiredFields(fieldIndex);
    if ~isfield(cfg, fieldName) || isempty(cfg.(fieldName))
        error("otfs_tr:MissingConfiguration", ...
            "Missing required configuration field: %s", fieldName);
    end
end

validTransportTypes = ["int8", "int16"];
if ~any(string(cfg.txTransportDataType) == validTransportTypes) || ...
        ~any(string(cfg.rxTransportDataType) == validTransportTypes)
    error("otfs_tr:InvalidTransportDataType", ...
        "TX and RX TransportDataType must be int8 or int16.");
end

if cfg.txAddress == cfg.rxAddress
    error("otfs_tr:SameRadioAddress", ...
        "TX and RX must use two different X310 IP addresses.");
end
if cfg.fsRx < cfg.fsTx || abs(cfg.fsRx/cfg.fsTx - round(cfg.fsRx/cfg.fsTx)) > 1e-12
    error("otfs_tr:InvalidSampleRateRatio", ...
        "fsRx/fsTx must be a positive integer.");
end
if cfg.MBits ~= log2(cfg.MMod) || mod(cfg.MBits, 1) ~= 0
    error("otfs_tr:InvalidModulationOrder", ...
        "MMod must provide an integer number of bits per symbol.");
end
if cfg.cpLen < 1 || cfg.cpLen > cfg.N*cfg.M
    error("otfs_tr:InvalidCyclicPrefix", ...
        "cpLen must be between 1 and N*M.");
end
if gcd(cfg.preambleLen, cfg.preambleRoot) ~= 1
    error("otfs_tr:InvalidPreambleRoot", ...
        "preambleLen and preambleRoot must be coprime.");
end
if max(abs(cfg.cfoSearchHz)) < abs(cfg.equivalentDopplerHz)
    error("otfs_tr:CfoSearchTooNarrow", ...
        "The CFO search grid does not cover equivalentDopplerHz.");
end
interpolation = cfg.masterClockRate/cfg.fsTx;
decimation = cfg.masterClockRate/cfg.fsRx;
if interpolation ~= round(interpolation) || decimation ~= round(decimation)
    error("otfs_tr:InvalidClockRateRatio", ...
        "Master-clock interpolation and decimation must be integers.");
end
if cfg.txBufferFrameCount < 2 || cfg.rxSamplesPerFrame < 1
    error("otfs_tr:InvalidHardwareBuffer", ...
        "TX and RX hardware buffer sizes must be positive and usable.");
end
if cfg.decodeFrameMarginRatio < 0
    error("otfs_tr:InvalidDecodeFrameMargin", ...
        "decodeFrameMarginRatio must be nonnegative.");
end
if cfg.maxDecodedFrames < cfg.minimumValidFrames
    error("otfs_tr:InsufficientDecodeFrameLimit", ...
        "maxDecodedFrames must be at least minimumValidFrames.");
end
if cfg.availableCaptureFrames < cfg.minimumValidFrames
    error("otfs_tr:CaptureWindowTooShort", ...
        "The RX window cannot contain the required number of complete frames.");
end
if cfg.maxDecodedFrames > cfg.availableCaptureFrames
    error("otfs_tr:DecodeFrameLimitExceedsCapture", ...
        "maxDecodedFrames cannot exceed the complete frames in the RX window.");
end
if cfg.designSpectralEfficiency < cfg.minimumSpectralEfficiency
    error("otfs_tr:SpectralEfficiencyNotMet", ...
        "Design spectral efficiency not met: %.6g < %.6g bit/s/Hz.", ...
        cfg.designSpectralEfficiency, cfg.minimumSpectralEfficiency);
end

if isfield(cfg, "targetTestBits") && ...
        (~isscalar(cfg.targetTestBits) || ~isfinite(cfg.targetTestBits) || ...
        cfg.targetTestBits < 1 || mod(cfg.targetTestBits, 1) ~= 0)
    error("otfs_tr:InvalidTargetTestBits", ...
        "targetTestBits must be a positive integer.");
end

if isfield(cfg, "superframeLength")
    validHeader = isscalar(cfg.superframeLength) && ...
        cfg.superframeLength >= 2 && mod(cfg.superframeLength, 1) == 0 && ...
        cfg.superframeLength <= 2^cfg.frameIdBits && ...
        cfg.frameCrcBits == 8 && ...
        isscalar(cfg.headerRepetition) && cfg.headerRepetition >= 1 && ...
        mod(cfg.headerRepetition, 2) == 1 && ...
        cfg.payloadBitsPerFrame > 0;
    if ~validHeader
        error("otfs_tr:InvalidSuperframeConfiguration", ...
            "Superframe length, header coding, or payload capacity is invalid.");
    end
    if mod(cfg.txBufferFrameCount, cfg.superframeLength) ~= 0
        error("otfs_tr:IncompleteTransmitSuperframe", ...
            "txBufferFrameCount must be a multiple of superframeLength.");
    end
    if cfg.totalUniquePayloadBits < cfg.minimumTestBits
        error("otfs_tr:InsufficientUniquePayloadBits", ...
            "One superframe must contain at least minimumTestBits unique bits.");
    end
    if cfg.maxDecodedFrames > cfg.superframeLength
        error("otfs_tr:DecodeLimitExceedsSuperframe", ...
            "maxDecodedFrames must not exceed superframeLength.");
    end
end

if isfield(cfg, "enableSfoCompensation") && cfg.enableSfoCompensation
    validSfo = isscalar(cfg.sfoMinimumPreambles) && ...
        cfg.sfoMinimumPreambles >= 2 && ...
        mod(cfg.sfoMinimumPreambles, 1) == 0 && ...
        isscalar(cfg.sfoMinCorrectionPpm) && ...
        cfg.sfoMinCorrectionPpm >= 0 && ...
        isscalar(cfg.sfoMaxAbsPpm) && ...
        cfg.sfoMaxAbsPpm > cfg.sfoMinCorrectionPpm && ...
        isscalar(cfg.sfoPreambleMinScore) && ...
        cfg.sfoPreambleMinScore > 0 && cfg.sfoPreambleMinScore <= 1;
    if ~validSfo
        error("otfs_tr:InvalidSfoConfiguration", ...
            "SFO thresholds and minimum preamble count are invalid.");
    end
end

if isfield(cfg, "enableFractionalTimingCompensation") && ...
        cfg.enableFractionalTimingCompensation
    searchSamples = cfg.fractionalTimingSearchSamples10;
    validFractionalTiming = isvector(searchSamples) && ...
        ~isempty(searchSamples) && all(isfinite(searchSamples)) && ...
        all(abs(searchSamples) <= 0.5) && ...
        any(abs(searchSamples) < 10*eps) && ...
        isscalar(cfg.fractionalTimingEstimationFrames) && ...
        cfg.fractionalTimingEstimationFrames >= 1 && ...
        mod(cfg.fractionalTimingEstimationFrames, 1) == 0 && ...
        isscalar(cfg.fractionalTimingMinImprovementRatio) && ...
        cfg.fractionalTimingMinImprovementRatio >= 1;
    if ~validFractionalTiming
        error("otfs_tr:InvalidFractionalTimingConfiguration", ...
            "Fractional-timing search grid or thresholds are invalid.");
    end
end

if isfield(cfg, "enableDdPilotResidualCfoFallback") && ...
        cfg.enableDdPilotResidualCfoFallback
    gridHz = cfg.ddPilotResidualCfoSearchHz;
    validFallback = isvector(gridHz) && ~isempty(gridHz) && ...
        all(isfinite(gridHz)) && any(abs(gridHz) < 10*eps) && ...
        isscalar(cfg.ddPilotResidualCfoTriggerHz) && ...
        cfg.ddPilotResidualCfoTriggerHz >= 0;
    if ~validFallback
        error("otfs_tr:InvalidDdPilotCfoFallbackConfiguration", ...
            "DD-pilot residual-CFO fallback settings are invalid.");
    end
end

if isfield(cfg, "enableStructuredRowBiasCorrection") && ...
        cfg.enableStructuredRowBiasCorrection
    validRowBias = isscalar(cfg.rowBiasIterations) && ...
        cfg.rowBiasIterations >= 1 && mod(cfg.rowBiasIterations, 1) == 0 && ...
        isscalar(cfg.rowBiasMinMagnitude) && cfg.rowBiasMinMagnitude >= 0 && ...
        isscalar(cfg.rowBiasMaxMagnitude) && ...
        cfg.rowBiasMaxMagnitude > cfg.rowBiasMinMagnitude && ...
        isscalar(cfg.rowBiasMinImprovementRatio) && ...
        cfg.rowBiasMinImprovementRatio >= 1 && ...
        isscalar(cfg.rowBiasMinCoherence) && ...
        cfg.rowBiasMinCoherence >= 0 && cfg.rowBiasMinCoherence <= 1;
    if ~validRowBias
        error("otfs_tr:InvalidRowBiasConfiguration", ...
            "Structured row-bias correction settings are invalid.");
    end
end

if isfield(cfg, "enableMpNoiseVarianceCalibration") && ...
        cfg.enableMpNoiseVarianceCalibration
    if ~isscalar(cfg.mpNoiseCalibrationMinRatio) || ...
            cfg.mpNoiseCalibrationMinRatio < 1
        error("otfs_tr:InvalidMpNoiseCalibrationConfiguration", ...
            "MP noise-calibration ratio must be at least one.");
    end
end
end
