function otfs_tr_validate_config(cfg)
%otfs_tr_validate_config Reject unsupported or unsafe OTFS-TR settings.

requiredFields = [
    "txAddress", "rxAddress", "txRadioConfiguration", ...
    "rxRadioConfiguration", "txAntenna", "rxAntenna", ...
    "masterClockRate", "fsTx", "fsRx", ...
    "signalBandwidthHz", "N", "M", "MMod", "MBits", "cpLen", ...
    "preambleLen", "preambleRoot", "txBufferFrameCount", ...
    "rxSamplesPerFrame", "maxDecodedFrames", "minimumValidFrames", ...
    "availableCaptureFrames", "decodeFrameMarginRatio", ...
    "cfoSearchHz", "cfoFineSearchStepHz", "equivalentDopplerHz", ...
    "txTransportDataType", "rxTransportDataType", ...
    "applicationEnabled", "applicationMaxPayloadBytes", ...
    "applicationMappedBitsPerFrame", "berTestBitsPerFrame"
    ];
for fieldIndex = 1:numel(requiredFields)
    fieldName = requiredFields(fieldIndex);
    if ~isfield(cfg, fieldName) || isempty(cfg.(fieldName))
        error("otfs_tr:MissingConfiguration", ...
            "Missing required configuration field: %s", fieldName);
    end
end

validTransportTypes = ["int8", "int16"];
if ~any(string(cfg.txTransportDataType) == validTransportTypes) || ...
        ~any(string(cfg.rxTransportDataType) == validTransportTypes)
    error("otfs_tr:InvalidTransportDataType", ...
        "TX and RX TransportDataType must be int8 or int16.");
end

if cfg.txAddress == cfg.rxAddress
    error("otfs_tr:SameRadioAddress", ...
        "TX and RX must use two different X310 IP addresses.");
end
% Older saved TX references have no rxCenterFrequencyHz; retain their
% offline-decode compatibility while checking all new RF configurations.
if isfield(cfg, "rxCenterFrequencyHz")
    validateattributes(cfg.rxCenterFrequencyHz, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
    validateattributes(cfg.txCenterFrequencyHz, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
    if abs(cfg.rxCenterFrequencyHz - cfg.txCenterFrequencyHz - ...
            cfg.equivalentDopplerHz) > 1e-6
        error("otfs_tr:InconsistentCenterFrequency", ...
            "equivalentDopplerHz must equal RX center minus TX center.");
    end
end
if cfg.fsRx < cfg.fsTx || abs(cfg.fsRx/cfg.fsTx - round(cfg.fsRx/cfg.fsTx)) > 1e-12
    error("otfs_tr:InvalidSampleRateRatio", ...
        "fsRx/fsTx must be a positive integer.");
end
if cfg.MBits ~= log2(cfg.MMod) || mod(cfg.MBits, 1) ~= 0
    error("otfs_tr:InvalidModulationOrder", ...
        "MMod must provide an integer number of bits per symbol.");
end
if cfg.cpLen < 1 || cfg.cpLen > cfg.N*cfg.M
    error("otfs_tr:InvalidCyclicPrefix", ...
        "cpLen must be between 1 and N*M.");
end
if gcd(cfg.preambleLen, cfg.preambleRoot) ~= 1
    error("otfs_tr:InvalidPreambleRoot", ...
        "preambleLen and preambleRoot must be coprime.");
end
if max(abs(cfg.cfoSearchHz)) < abs(cfg.equivalentDopplerHz)
    error("otfs_tr:CfoSearchTooNarrow", ...
        "The CFO search grid does not cover equivalentDopplerHz.");
end
interpolation = cfg.masterClockRate/cfg.fsTx;
decimation = cfg.masterClockRate/cfg.fsRx;
if interpolation ~= round(interpolation) || decimation ~= round(decimation)
    error("otfs_tr:InvalidClockRateRatio", ...
        "Master-clock interpolation and decimation must be integers.");
end
if cfg.txBufferFrameCount < 2 || cfg.rxSamplesPerFrame < 1
    error("otfs_tr:InvalidHardwareBuffer", ...
        "TX and RX hardware buffer sizes must be positive and usable.");
end
if cfg.decodeFrameMarginRatio < 0
    error("otfs_tr:InvalidDecodeFrameMargin", ...
        "decodeFrameMarginRatio must be nonnegative.");
end
if cfg.maxDecodedFrames < cfg.minimumValidFrames
    error("otfs_tr:InsufficientDecodeFrameLimit", ...
        "maxDecodedFrames must be at least minimumValidFrames.");
end
if cfg.availableCaptureFrames < cfg.minimumValidFrames
    error("otfs_tr:CaptureWindowTooShort", ...
        "The RX window cannot contain the required number of complete frames.");
end
if cfg.maxDecodedFrames > cfg.availableCaptureFrames
    error("otfs_tr:DecodeFrameLimitExceedsCapture", ...
        "maxDecodedFrames cannot exceed the complete frames in the RX window.");
end
if cfg.designSpectralEfficiency < cfg.minimumSpectralEfficiency
    error("otfs_tr:SpectralEfficiencyNotMet", ...
        "Design spectral efficiency not met: %.6g < %.6g bit/s/Hz.", ...
        cfg.designSpectralEfficiency, cfg.minimumSpectralEfficiency);
end
if cfg.applicationMappedBitsPerFrame < 0 || ...
        cfg.applicationMappedBitsPerFrame > cfg.payloadBitsPerFrame || ...
        cfg.berTestBitsPerFrame < 1 || ...
        cfg.effectiveBitsPerFrame ~= cfg.berTestBitsPerFrame
    error("otfs_tr:InvalidApplicationPayloadCapacity", ...
        "Application and BER regions do not fit in one OTFS payload.");
end
if cfg.applicationEnabled && ...
        (cfg.MMod ~= 8 || cfg.applicationMaxPayloadBytes < 1 || ...
        cfg.applicationPacketBits > cfg.applicationMappedBitsPerFrame)
    error("otfs_tr:InvalidApplicationConfiguration", ...
        "The short application payload must fit the configured 8-QAM region.");
end

if isfield(cfg, "enableTxAwgn")
    validEnable = (islogical(cfg.enableTxAwgn) || ...
        isnumeric(cfg.enableTxAwgn)) && isscalar(cfg.enableTxAwgn) && ...
        isfinite(double(cfg.enableTxAwgn)) && ...
        any(double(cfg.enableTxAwgn) == [0 1]);
    requiredAwgnFieldsPresent = isfield(cfg, "txAwgnSnrDb") && ...
        isfield(cfg, "txAwgnSeed") && isfield(cfg, "hardwareTxPeak");
    if ~validEnable || ~requiredAwgnFieldsPresent
        error("otfs_tr:InvalidTxAwgnConfiguration", ...
            "TX AWGN enable, SNR, seed, or peak limit is invalid.");
    end
    validSnr = isnumeric(cfg.txAwgnSnrDb) && ...
        isscalar(cfg.txAwgnSnrDb) && isreal(cfg.txAwgnSnrDb) && ...
        isfinite(cfg.txAwgnSnrDb) && cfg.txAwgnSnrDb >= 0 && ...
        cfg.txAwgnSnrDb <= 100;
    validSeed = isnumeric(cfg.txAwgnSeed) && ...
        isscalar(cfg.txAwgnSeed) && isreal(cfg.txAwgnSeed) && ...
        isfinite(cfg.txAwgnSeed) && cfg.txAwgnSeed >= 0 && ...
        cfg.txAwgnSeed <= 2^32-1 && mod(cfg.txAwgnSeed, 1) == 0;
    validPeak = isnumeric(cfg.hardwareTxPeak) && ...
        isscalar(cfg.hardwareTxPeak) && isreal(cfg.hardwareTxPeak) && ...
        isfinite(cfg.hardwareTxPeak) && cfg.hardwareTxPeak > 0;
    if ~validSnr || ~validSeed || ~validPeak
        error("otfs_tr:InvalidTxAwgnConfiguration", ...
            "TX AWGN SNR must be 0..100 dB, seed must be uint32-compatible, and peak must be positive.");
    end
end
if isfield(cfg, "frameCaseIdBits") && cfg.frameCaseIdBits > 0
    expectedInformationBits = cfg.frameIdBits + ...
        cfg.frameCaseIdBits + cfg.frameCrcBits;
    expectedCodedBits = expectedInformationBits*cfg.headerRepetition;
    expectedHeaderSymbols = ceil(expectedCodedBits/cfg.MBits);
    if cfg.frameCaseIdBits ~= 32 || cfg.applicationEnabled || ...
            cfg.headerInformationBits ~= expectedInformationBits || ...
            cfg.headerCodedBits ~= expectedCodedBits || ...
            cfg.headerSymbolsPerFrame ~= expectedHeaderSymbols || ...
            cfg.payloadSymbolsPerFrame ~= ...
            cfg.dataSymbolsPerFrame-expectedHeaderSymbols || ...
            cfg.payloadBitsPerFrame ~= ...
            cfg.payloadSymbolsPerFrame*cfg.MBits || ...
            cfg.berTestBitsPerFrame ~= cfg.payloadBitsPerFrame
        error("otfs_tr:InvalidAirCaseConfiguration", ...
            "The air case code and payload capacities are inconsistent.");
    end
end

if isfield(cfg, "targetTestBits") && ...
        (~isscalar(cfg.targetTestBits) || ~isfinite(cfg.targetTestBits) || ...
        cfg.targetTestBits < 1 || mod(cfg.targetTestBits, 1) ~= 0)
    error("otfs_tr:InvalidTargetTestBits", ...
        "targetTestBits must be a positive integer.");
end

if isfield(cfg, "superframeLength")
    validHeader = isscalar(cfg.superframeLength) && ...
        cfg.superframeLength >= 2 && mod(cfg.superframeLength, 1) == 0 && ...
        cfg.superframeLength <= 2^cfg.frameIdBits && ...
        cfg.frameCrcBits == 8 && ...
        isscalar(cfg.headerRepetition) && cfg.headerRepetition >= 1 && ...
        mod(cfg.headerRepetition, 2) == 1 && ...
        cfg.payloadBitsPerFrame > 0;
    if ~validHeader
        error("otfs_tr:InvalidSuperframeConfiguration", ...
            "Superframe length, header coding, or payload capacity is invalid.");
    end
    if mod(cfg.txBufferFrameCount, cfg.superframeLength) ~= 0
        error("otfs_tr:IncompleteTransmitSuperframe", ...
            "txBufferFrameCount must be a multiple of superframeLength.");
    end
    if cfg.totalUniquePayloadBits < cfg.minimumTestBits
        error("otfs_tr:InsufficientUniquePayloadBits", ...
            "One superframe must contain at least minimumTestBits unique bits.");
    end
    if cfg.maxDecodedFrames > cfg.superframeLength
        error("otfs_tr:DecodeLimitExceedsSuperframe", ...
            "maxDecodedFrames must not exceed superframeLength.");
    end
end

if isfield(cfg, "enableSfoCompensation") && cfg.enableSfoCompensation
    validSfo = isscalar(cfg.sfoMinimumPreambles) && ...
        cfg.sfoMinimumPreambles >= 2 && ...
        mod(cfg.sfoMinimumPreambles, 1) == 0 && ...
        isscalar(cfg.sfoMinCorrectionPpm) && ...
        cfg.sfoMinCorrectionPpm >= 0 && ...
        isscalar(cfg.sfoMaxAbsPpm) && ...
        cfg.sfoMaxAbsPpm > cfg.sfoMinCorrectionPpm && ...
        isscalar(cfg.sfoPreambleMinScore) && ...
        cfg.sfoPreambleMinScore > 0 && cfg.sfoPreambleMinScore <= 1;
    if ~validSfo
        error("otfs_tr:InvalidSfoConfiguration", ...
            "SFO thresholds and minimum preamble count are invalid.");
    end
end

if isfield(cfg, "enableFractionalTimingCompensation") && ...
        cfg.enableFractionalTimingCompensation
    searchSamples = cfg.fractionalTimingSearchSamples10;
    validFractionalTiming = isvector(searchSamples) && ...
        ~isempty(searchSamples) && all(isfinite(searchSamples)) && ...
        all(abs(searchSamples) <= 0.5) && ...
        any(abs(searchSamples) < 10*eps) && ...
        isscalar(cfg.fractionalTimingEstimationFrames) && ...
        cfg.fractionalTimingEstimationFrames >= 1 && ...
        mod(cfg.fractionalTimingEstimationFrames, 1) == 0 && ...
        isscalar(cfg.fractionalTimingMinImprovementRatio) && ...
        cfg.fractionalTimingMinImprovementRatio >= 1;
    if ~validFractionalTiming
        error("otfs_tr:InvalidFractionalTimingConfiguration", ...
            "Fractional-timing search grid or thresholds are invalid.");
    end
end

if isfield(cfg, "enableDdPilotResidualCfoFallback") && ...
        cfg.enableDdPilotResidualCfoFallback
    gridHz = cfg.ddPilotResidualCfoSearchHz;
    validFallback = isvector(gridHz) && ~isempty(gridHz) && ...
        all(isfinite(gridHz)) && any(abs(gridHz) < 10*eps) && ...
        isscalar(cfg.ddPilotResidualCfoTriggerHz) && ...
        cfg.ddPilotResidualCfoTriggerHz >= 0;
    if ~validFallback
        error("otfs_tr:InvalidDdPilotCfoFallbackConfiguration", ...
            "DD-pilot residual-CFO fallback settings are invalid.");
    end
end

if isfield(cfg, "enableStructuredRowBiasCorrection") && ...
        cfg.enableStructuredRowBiasCorrection
    validRowBias = isscalar(cfg.rowBiasIterations) && ...
        cfg.rowBiasIterations >= 1 && mod(cfg.rowBiasIterations, 1) == 0 && ...
        isscalar(cfg.rowBiasMinMagnitude) && cfg.rowBiasMinMagnitude >= 0 && ...
        isscalar(cfg.rowBiasMaxMagnitude) && ...
        cfg.rowBiasMaxMagnitude > cfg.rowBiasMinMagnitude && ...
        isscalar(cfg.rowBiasMinImprovementRatio) && ...
        cfg.rowBiasMinImprovementRatio >= 1 && ...
        isscalar(cfg.rowBiasMinCoherence) && ...
        cfg.rowBiasMinCoherence >= 0 && cfg.rowBiasMinCoherence <= 1;
    if ~validRowBias
        error("otfs_tr:InvalidRowBiasConfiguration", ...
            "Structured row-bias correction settings are invalid.");
    end
end

if isfield(cfg, "enableMpNoiseVarianceCalibration") && ...
        cfg.enableMpNoiseVarianceCalibration
    if ~isscalar(cfg.mpNoiseCalibrationMinRatio) || ...
            cfg.mpNoiseCalibrationMinRatio < 1
        error("otfs_tr:InvalidMpNoiseCalibrationConfiguration", ...
            "MP noise-calibration ratio must be at least one.");
    end
end
if isfield(cfg, "mpMaximumIterations") && ...
        (~isscalar(cfg.mpMaximumIterations) || ...
        ~isfinite(cfg.mpMaximumIterations) || ...
        cfg.mpMaximumIterations < 1 || ...
        mod(cfg.mpMaximumIterations, 1) ~= 0)
    error("otfs_tr:InvalidMpMaximumIterations", ...
        "MP maximum iterations must be a positive integer.");
end

if isfield(cfg, "enableSharedMpNoiseCalibration")
    validEnable = (islogical(cfg.enableSharedMpNoiseCalibration) || ...
        isnumeric(cfg.enableSharedMpNoiseCalibration)) && ...
        isscalar(cfg.enableSharedMpNoiseCalibration) && ...
        isfinite(double(cfg.enableSharedMpNoiseCalibration)) && ...
        any(double(cfg.enableSharedMpNoiseCalibration) == [0 1]);
    requiredSharedFieldsPresent = ...
        isfield(cfg, "sharedMpNoiseCalibrationFrames") && ...
        isfield(cfg, "sharedMpNoiseCalibrationMinimumValidFrames");
    if ~validEnable || ~requiredSharedFieldsPresent
        error("otfs_tr:InvalidSharedMpNoiseCalibrationConfiguration", ...
            "Shared MP noise-calibration settings are incomplete or invalid.");
    end
    validCalibrationFrames = ...
        isscalar(cfg.sharedMpNoiseCalibrationFrames) && ...
        isfinite(cfg.sharedMpNoiseCalibrationFrames) && ...
        cfg.sharedMpNoiseCalibrationFrames >= 1 && ...
        mod(cfg.sharedMpNoiseCalibrationFrames, 1) == 0;
    validMinimumFrames = ...
        isscalar(cfg.sharedMpNoiseCalibrationMinimumValidFrames) && ...
        isfinite(cfg.sharedMpNoiseCalibrationMinimumValidFrames) && ...
        cfg.sharedMpNoiseCalibrationMinimumValidFrames >= 1 && ...
        mod(cfg.sharedMpNoiseCalibrationMinimumValidFrames, 1) == 0 && ...
        cfg.sharedMpNoiseCalibrationMinimumValidFrames <= ...
        cfg.sharedMpNoiseCalibrationFrames;
    if ~validCalibrationFrames || ~validMinimumFrames
        error("otfs_tr:InvalidSharedMpNoiseCalibrationConfiguration", ...
            "Shared calibration frame counts must be positive and internally consistent.");
    end
end

if isfield(cfg, "enableFrameParallel")
    validEnable = (islogical(cfg.enableFrameParallel) || ...
        isnumeric(cfg.enableFrameParallel)) && ...
        isscalar(cfg.enableFrameParallel) && ...
        isfinite(double(cfg.enableFrameParallel)) && ...
        any(double(cfg.enableFrameParallel) == [0 1]);
    requiredParallelFieldsPresent = ...
        isfield(cfg, "frameParallelWorkers") && ...
        isfield(cfg, "frameParallelMinimumFrames");
    if ~validEnable || ~requiredParallelFieldsPresent
        error("otfs_tr:InvalidFrameParallelConfiguration", ...
            "Frame-parallel enable and worker settings are invalid.");
    end
    validWorkers = isscalar(cfg.frameParallelWorkers) && ...
        isfinite(cfg.frameParallelWorkers) && ...
        cfg.frameParallelWorkers >= 1 && ...
        mod(cfg.frameParallelWorkers, 1) == 0;
    validMinimumFrames = isscalar(cfg.frameParallelMinimumFrames) && ...
        isfinite(cfg.frameParallelMinimumFrames) && ...
        cfg.frameParallelMinimumFrames >= 2 && ...
        mod(cfg.frameParallelMinimumFrames, 1) == 0;
    if ~validWorkers || ~validMinimumFrames
        error("otfs_tr:InvalidFrameParallelConfiguration", ...
            "Frame-parallel workers must be positive and the minimum frame count must be at least two.");
    end
end

if isfield(cfg, "enableProgressReporting")
    validEnable = (islogical(cfg.enableProgressReporting) || ...
        isnumeric(cfg.enableProgressReporting)) && ...
        isscalar(cfg.enableProgressReporting) && ...
        isfinite(double(cfg.enableProgressReporting)) && ...
        any(double(cfg.enableProgressReporting) == [0 1]);
    requiredProgressFieldsPresent = ...
        isfield(cfg, "progressFile") && ...
        isfield(cfg, "progressUpdateEveryBits");
    if ~validEnable || ~requiredProgressFieldsPresent
        error("otfs_tr:InvalidProgressConfiguration", ...
            "Progress reporting settings are incomplete or invalid.");
    end
    validBitInterval = isscalar(cfg.progressUpdateEveryBits) && ...
        isfinite(cfg.progressUpdateEveryBits) && ...
        cfg.progressUpdateEveryBits >= 1 && ...
        mod(cfg.progressUpdateEveryBits, 1) == 0;
    if ~validBitInterval
        error("otfs_tr:InvalidProgressConfiguration", ...
            "The progress BER interval must be a positive integer bit count.");
    end
end

if isfield(cfg, "saveFullDiagnostics")
    validEnable = (islogical(cfg.saveFullDiagnostics) || ...
        isnumeric(cfg.saveFullDiagnostics)) && ...
        isscalar(cfg.saveFullDiagnostics) && ...
        isfinite(double(cfg.saveFullDiagnostics)) && ...
        any(double(cfg.saveFullDiagnostics) == [0 1]);
    validFrames = isfield(cfg, "savedFullDiagnosticFrames") && ...
        isnumeric(cfg.savedFullDiagnosticFrames) && ...
        isvector(cfg.savedFullDiagnosticFrames) && ...
        all(isfinite(cfg.savedFullDiagnosticFrames)) && ...
        all(cfg.savedFullDiagnosticFrames >= 1) && ...
        all(mod(cfg.savedFullDiagnosticFrames, 1) == 0);
    if ~validEnable || ~validFrames
        error("otfs_tr:InvalidDiagnosticStorageConfiguration", ...
            "Saved diagnostic-frame settings are invalid.");
    end
end

if isfield(cfg, "generateDiagnosticArtifacts")
    validEnable = (islogical(cfg.generateDiagnosticArtifacts) || ...
        isnumeric(cfg.generateDiagnosticArtifacts)) && ...
        isscalar(cfg.generateDiagnosticArtifacts) && ...
        isfinite(double(cfg.generateDiagnosticArtifacts)) && ...
        any(double(cfg.generateDiagnosticArtifacts) == [0 1]);
    if ~validEnable
        error("otfs_tr:InvalidDiagnosticArtifactConfiguration", ...
            "Diagnostic artifact generation must be a logical scalar.");
    end
end
end
