function otfs_tr_write_progress_text_atomic(filePath, progress)
%otfs_tr_write_progress_text_atomic Atomically publish key=value progress.

fieldNames = [ ...
    "version", "stage", "updated_at", "update_sequence", ...
    "completed_frames", "total_frames", "progress_fraction", ...
    "valid_frames_so_far", "tested_bits_so_far", ...
    "bit_errors_so_far", "ber_update_interval_bits", ...
    "ber_update_count", "is_ber_update", "ber_so_far", ...
    "parallel_workers", "data_queue_used", ...
    "detection_elapsed_seconds"];
otfs_tr_write_key_value_atomic(filePath, progress, fieldNames);
end
