function referenceFile = otfs_tr_prepare_local_reference( ...
        cfg, equivalentDopplerHz, testCaseFile, pair)
%otfs_tr_prepare_local_reference Rebuild the RX comparison bits locally.
% The same MAT test case must be present on both computers. This does not
% establish that the remote TX completed or transmitted these exact bits.

cfg = otfs_tr_apply_test_case_mode(cfg);
testCase = otfs_tr_load_test_case(testCaseFile, cfg);
requestedCfoKnown = isscalar(equivalentDopplerHz) && ...
    isnumeric(equivalentDopplerHz) && isfinite(equivalentDopplerHz);
if requestedCfoKnown
    localReferenceCfoHz = double(equivalentDopplerHz);
else
    % CFO does not change the reference bits or nominal baseband waveform.
    % Use coincident local RF centers only to keep the synthetic reference
    % configuration self-consistent; the received CFO is estimated later.
    localReferenceCfoHz = 0;
end
cfg = otfs_tr_apply_equivalent_cfo(cfg, localReferenceCfoHz);
request = struct("protocol_version", cfg.controlProtocolVersion, ...
    "command", "start_test", ...
    "test_case_file", string(testCaseFile), ...
    "equivalent_cfo_hz", localReferenceCfoHz, ...
    "options", struct("duration_seconds", ...
    cfg.defaultTransmitDurationSeconds));
request = otfs_tr_validate_request(request, cfg);
[~, reference, params, training] = ...
    otfs_tr_build_waveform(cfg, request, testCase);
txStatus = struct("started", false, "completed", false, ...
    "anyTxUnderrun", false, "executionMode", "rx-local-reference", ...
    "underrunMonitoringAvailable", false);
referenceOrigin = "rx-local-test-case";
requestedEquivalentCfoHz = equivalentDopplerHz;
referenceFile = string(pair.expectedReferenceFile);
if isfile(referenceFile)
    error("otfs_tr:ReferenceAlreadyExists", ...
        "Reference already exists for local run %s: %s", ...
        pair.runId, referenceFile);
end
save(referenceFile, "cfg", "params", "training", "reference", ...
    "txStatus", "request", "referenceOrigin", "requestedCfoKnown", ...
    "requestedEquivalentCfoHz", "-v7.3");
end
