function response = otfs_tr_build_software_response(result, stage)
%otfs_tr_build_software_response Build the stable v1 software result contract.

if nargin < 2
    stage = "artifacts_completed";
end
stage = string(stage);
if ~ismember(stage, ["metrics_completed", "artifacts_completed"])
    error("otfs_tr:InvalidResponseStage", ...
        "Response stage must be metrics_completed or artifacts_completed.");
end

response = struct();
response.protocol_version = "1.0";
response.command = "process_test";
response.local_run_id = string(localField(result, "localRunId", ""));
response.code = 0;
response.error_code = "OK";
response.stage = stage;
if stage == "metrics_completed"
    response.message = "Metrics completed; artifacts are pending.";
    response.status = "processing";
else
    response.message = "Signal processing completed.";
    response.status = "completed";
end
response.reference_origin = string(localField( ...
    result, "referenceOrigin", "tx-saved-reference"));
response.test_case_id = string(localField(result, "testCaseId", ""));
response.air_case_code_hex = "";
if isfield(result, "airCaseCode")
    response.air_case_code_hex = string(dec2hex(result.airCaseCode, 8));
end
response.air_case_code_confirmed = logical(localField( ...
    result, "airCaseCodeConfirmed", false));
response.transmitter_status_verified = logical(localField( ...
    result, "transmitterStatusVerified", true));

application = result.application;
response.application = struct( ...
    "transmitted_text", string(application.transmittedText), ...
    "decoded_text", string(application.decodedText), ...
    "encoding", "UTF-8", ...
    "payload_bytes", application.payloadBytes, ...
    "crc_pass", logical(application.crcPass), ...
    "text_match", logical(application.textMatch), ...
    "consistent_frames", application.consistentFrames, ...
    "pass", logical(application.pass));

response.metrics = struct( ...
    "modulation", "8-QAM", ...
    "cfo_assessment_source", string(localField(result, ...
    "cfoAssessmentSource", "configured_cfo")), ...
    "requested_equivalent_cfo_hz", result.requestedDopplerHz, ...
    "tested_equivalent_cfo_hz", result.acceptance.testedDopplerHz, ...
    "estimated_cfo_hz", result.cfoEstimateHz, ...
    "residual_cfo_hz", result.residualCfoHz, ...
    "estimated_sfo_ppm", localNestedField( ...
    result, "sfoInfo", "estimatedPpm", NaN), ...
    "valid_frames", result.validFrames, ...
    "tested_bits", result.totalBits, ...
    "received_bits_for_transfer_rate", localField(result, ...
    "receivedBitsForRate", result.totalBits), ...
    "receive_duration_seconds", localField(result, ...
    "receiveDurationSeconds", NaN), ...
    "transfer_rate_bps", localField(result, "transferRateBps", NaN), ...
    "transfer_rate_mbps", localField(result, "transferRateBps", NaN)/1e6, ...
    "bit_errors", result.totalErrors, ...
    "ber", result.ber, ...
    "zero_error_upper_95", result.zeroErrorBerUpper95, ...
    "design_spectral_efficiency_bit_s_hz", ...
    result.designSpectralEfficiency, ...
    "evm_percent", result.softEvmPercentMedian);

acceptance = result.acceptance;
response.acceptance = struct( ...
    "application_pass", logical(application.pass), ...
    "ber_pass", logical(acceptance.berPass), ...
    "tested_bits_pass", logical(acceptance.testBitsPass), ...
    "valid_frames_pass", logical(acceptance.validFramesPass), ...
    "cfo_pass", logical(acceptance.cfoEstimatePass && ...
    acceptance.residualCfoPass && acceptance.dopplerPass), ...
    "spectral_efficiency_pass", logical(acceptance.spectralEfficiencyPass), ...
    "radio_pass", logical(acceptance.radioPass), ...
    "core_metrics_pass", logical(acceptance.coreMetricsPass), ...
    "overall_pass", logical(result.overallPass));

constellationPath = localConstellationPath(result);
artifactsCompleted = stage == "artifacts_completed";
response.artifacts = struct( ...
    "status", localArtifactStatus(artifactsCompleted), ...
    "constellation_image_path", constellationPath, ...
    "result_mat_path", string(result.report.matFile), ...
    "report_text_path", string(result.report.textFile), ...
    "constellation_image_ready", artifactsCompleted && ...
    strlength(constellationPath) > 0, ...
    "result_mat_ready", artifactsCompleted, ...
    "report_text_ready", true);
response.updated_at = string(datetime("now", ...
    "TimeZone", "Asia/Shanghai", ...
    "Format", "yyyy-MM-dd'T'HH:mm:ssXXX"));
if artifactsCompleted
    response.completed_at = response.updated_at;
else
    response.completed_at = "";
end
end

function status = localArtifactStatus(completed)
if completed
    status = "completed";
else
    status = "pending";
end
end

function value = localField(s, name, defaultValue)
if isfield(s, name)
    value = s.(name);
else
    value = defaultValue;
end
end

function value = localNestedField(s, parentName, name, defaultValue)
value = defaultValue;
if isfield(s, parentName) && isfield(s.(parentName), name)
    value = s.(parentName).(name);
end
end

function path = localConstellationPath(result)
path = "";
if ~isfield(result, "diagnosticPlotFiles")
    return;
end
files = string(result.diagnosticPlotFiles);
match = contains(files, "constellation_8qam.png");
if any(match)
    path = files(find(match, 1, "first"));
end
end
